package com.biblioteca.enums;

public enum TipoContenido {
  LIBRO_FISICO,
  LIBRO_DIGITAL,
  AUDIO_LIBRO,
  REVISTA_FISICA,
  REVISTA_DIGITAL,
  COMIC_FISICO,
  COMIC_DIGITAL,
  MANGA_FISICO,
  MANGA_DIGITAL,
  
  MATERIAL_EDUCATIVO_DIGITAL,
  CONTENIDO_MULTIMEDIA_DIGITAL,
  
}